language: python
before_install:
  - chmod +x ./flaskapp/st.sh
install:
  - pip install flask
  - pip install gunicorn
  - pip install requests
  - pip install flask-bootstrap
  - pip install flask-wtf
  - pip install pillow
  - pip install tensorflow==2.0.0-alpha0
  - pip install keras
script:
  - cd flaskapp
  - ./st.sh
